"""add_payment_promo_code_models_and_privacy_models

Revision ID: e5836296f815
Revises: dd6862e42a32
Create Date: 2025-04-02 20:41:08.508261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5836296f815'
down_revision: Union[str, None] = 'dd6862e42a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_retention_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudonym_id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('records_affected', sa.Integer(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('operation_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_logs_pseudonym_id'), 'data_retention_logs', ['pseudonym_id'], unique=False)
    op.create_table('dialogue_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_content', sa.LargeBinary(), nullable=False),
    sa.Column('iv', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudonym_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_logs_created_at', 'error_logs', ['created_at'], unique=False)
    op.create_index('idx_error_logs_pseudonym_type', 'error_logs', ['pseudonym_id', 'error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_pseudonym_id'), 'error_logs', ['pseudonym_id'], unique=False)
    op.create_index(op.f('ix_error_logs_user_id'), 'error_logs', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('feedback_date', sa.DateTime(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('user_encryption_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_salt', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_pseudonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('pseudonym_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudonym_id')
    )
    op.create_table('dialogue_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudonym_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['dialogue_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_metadata_pseudonym_id'), 'dialogue_metadata', ['pseudonym_id'], unique=False)
    op.create_index(op.f('ix_dialogue_metadata_timestamp'), 'dialogue_metadata', ['timestamp'], unique=False)
    op.create_table('promo_code_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('promo_code', sa.String(length=50), nullable=False),
    sa.Column('credits_granted', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['promo_code'], ['promo_codes.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_code_usage_user_id'), 'promo_code_usage', ['user_id'], unique=False)
    op.drop_table('exercise_feedback')
    op.alter_column('payment_history', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_credits', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_credits', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('payment_history', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('exercise_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('exercise_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('exercise_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('feedback_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exercise_feedback_pkey')
    )
    op.drop_index(op.f('ix_promo_code_usage_user_id'), table_name='promo_code_usage')
    op.drop_table('promo_code_usage')
    op.drop_index(op.f('ix_dialogue_metadata_timestamp'), table_name='dialogue_metadata')
    op.drop_index(op.f('ix_dialogue_metadata_pseudonym_id'), table_name='dialogue_metadata')
    op.drop_table('dialogue_metadata')
    op.drop_table('user_pseudonyms')
    op.drop_table('user_encryption_keys')
    op.drop_table('promo_codes')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_error_logs_user_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_pseudonym_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_index('idx_error_logs_pseudonym_type', table_name='error_logs')
    op.drop_index('idx_error_logs_created_at', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_table('dialogue_content')
    op.drop_index(op.f('ix_data_retention_logs_pseudonym_id'), table_name='data_retention_logs')
    op.drop_table('data_retention_logs')
    # ### end Alembic commands ###
